x-environment:
  &default-environment
  POSTGRES_USER: vscode
  POSTGRES_PASSWORD: notsecure
  POSTGRES_DB: simplewebstore
services:
  pg:
    image: "postgres:16"
    restart: unless-stopped
    environment: *default-environment
    ports:
      - 15432:5432
    volumes:
      - pg-data:/var/lib/postgresql/data/
  frontend:
    build:
      context: .
      dockerfile: ./apps/frontend/Dockerfile
    ports:
      - "13000:3000"
    environment:
      - NEXT_PUBLIC_CLIENT_API="http://127.0.0.1:3001/api"
volumes:
  pg-data: